### ISSUE TITLE
Missing Door Hash at Rio del Lobo Rock

### ISSUE THREAD

**Issue by SimpleSandman** [femga/rdr3_discoveries#25]
Approximate coordinates: -3481.534, -3469.404, -0.8164485

![image](https://user-images.githubusercontent.com/14926100/166179667-539c7501-b20a-4f94-82bc-10292c0dfd03.png)

![image](https://user-images.githubusercontent.com/14926100/166179733-d84693bf-5895-47b1-a174-b1ac7c005ea6.png)

**Comment by femga** [comment]
@SimpleSandman This entity dont have door extension (as can be seen in file rdl_house_01_int.ytyp).
