### ISSUE TITLE
Missing Interior Entity Sets

### ISSUE THREAD

**Issue by SimpleSandman** [femga/rdr3_discoveries#27]
Great work on adding the missing sets BTW!

Now I'm looking for the entity sets for these interior IDs:
- 3586
- 13826
- 54530

I can see them in the [interiors_coords_and_hashes.lua](https://github.com/femga/rdr3_discoveries/blob/master/interiors/interiors_coords_and_hashes.lua) file with their hash types, but I don't see the entity sets in the [.../interior_sets/README.md](https://github.com/femga/rdr3_discoveries/blob/master/interiors/interior_sets/README.md).

**Comment by femga** [comment]
@SimpleSandman YTYP files for these interiors dont have entity sets.
