### ISSUE TITLE
Hashes for Beta Black Duster Coat "player_zero_coat_open_001" and "player_zero_coat_001_open"

### ISSUE THREAD

**Issue by edcar007** [femga/rdr3_discoveries#29]
It's the beta black duster coat which doesn't spawn with any of the given hashes from hash generator.
Is there anyway a hash can be found for it?

I tried it on both PC and PS4 1.00 with save editor/ save wizard with the hashes from hash generator.
None of them worked unless I used a mod for the PC version.

The files for the beta coat are:

player_zero_coat_001
player_zero_coat_open_001

Thanks!

**Comment by femga** [comment]
@edcar007 
Dont know what duster coat you speak about. Some of these?
clothing_hl_player_coat_001_10
clothing_hl_player_coat_001_11
clothing_hl_player_coat_001_12
clothing_hl_player_coat_001_13
clothing_hl_player_coat_001_14
clothing_hl_player_coat_001_16
clothing_hl_player_coat_001_17
clothing_hl_player_coat_001_18
clothing_hl_player_coat_001_1
clothing_hl_player_coat_001_20
clothing_hl_player_coat_001_3
clothing_hl_player_coat_001_4
clothing_hl_player_coat_001_5
clothing_hl_player_coat_001_6
clothing_hl_player_coat_001_7
clothing_hl_player_coat_001_9

**Comment by edcar007** [comment]
![unknown](https://user-images.githubusercontent.com/110544487/183067895-db64c94e-d0b9-444f-b8f2-80aa7d4b4fc8.png)

It is this coat that goes unused in the final game.
The only way to spawn it right now is to use rampage trainer on PC via this mod:
https://www.nexusmods.com/reddeadredemption2/mods/511
It basically replaces the final duster coat with the beta one.

I am looking for a way to spawn it via save editor using the right hash on PS4.

I did find the coat hashes you provided in cloth_hash_names.lua, I haven't tested these yet as my PC has given up on me.
I am waiting for a friend to confirm these work, hopefully they are not color variations of the final duster.

**Comment by Disquse** [comment]
>  The only way to spawn it right now is to use rampage trainer on PC via this mod:

Or make and stream proper meta files.

**Comment by edcar007** [comment]
> > The only way to spawn it right now is to use rampage trainer on PC via this mod:
> 
> Or make and stream proper meta files.

That's exactly what Rampage trainer did with the mod.
It streamed player_zero_coat_001.yld and .ydd and replaced the final one.
At least, that's how I did it a year ago on the PC version.

I obviously can't do that with the PS4 version, so finding the right hash for it is the goal.

**Comment by Disquse** [comment]
> It streamed player_zero_coat_001.yld and .ydd and replaced the final one.

Replacing isn't a "proper" way to stream such stuff. I meant adding this component as a new one, without replacing anything. This would be the proper way.
