### ISSUE TITLE
BLIP_ADD_FOR_RADIUS

### ISSUE THREAD

**Issue by XakraD** [femga/rdr3_discoveries#31]
Hello, I wanted to ask if you have a blip radius list. I have searched the repository for the native one (0x45f13b7e0a15c880) in case it comes out in some example and the hashes of several radius blips, and I have not found them. In case you don't have them, I found a list.

**Comment by femga** [comment]
@XakraD  Native 0x45f13b7e0a15c880 uses the same blip styles as here: https://github.com/femga/rdr3_discoveries/tree/master/useful_info_from_rpfs/blip_styles

But any other discovery information you can find is welcome.
