### ISSUE TITLE
Discovered natives by community false line 11

### ISSUE THREAD

**Issue by elkCODE** [femga/rdr3_discoveries#32]
Instead of the line 11 which states you need to change to arthur_healthy after the injured_ walkingstyles i, for one, found it only work with normal at the native 0x89F5E7ADECCCB49C.

**Comment by femga** [comment]
@elkCODE yea, use native 0x89F5E7ADECCCB49C to clear loco motion. "Discovered natives" is deprecated stuff (it is 3 years old, much more discovered since). I'll probably delete this to not confuse people.
