### ISSUE TITLE
Missing music event names

### ISSUE THREAD

**Issue by Anterag1400** [femga/rdr3_discoveries#51]
So, I'm after the RDR2 music variations.

I checked music_events.lua (thank you femga for finding these names) and it looks like some names are missing, such as for example the Territories event names (like ride, encounters, etc).

I have some questions:

The first is, were these names found in the decompiled mission scripts (https://github.com/kepmehz/RDR3-Decompiled-Scripts), while Territories probably don't have an associated mission script so they weren't part of the list?

The next question is, were these names found in dumped memory from the game? Aren't those names encrypted?

Indeed, I dumped the game memory from the title screen (since that's when sound tables should be loaded in memory
), and the sound table file is encrypted (since I think the table in RDR2 would tell us which layers are used) since I don't see plain text names after the sound table.

Thanks in advance.

**Comment by Anterag1400** [comment]
Thanks for the response. I mean, there are music event names probably for Territories tracks, like Heartlands riding and no riding, and encounter tracks.

**Comment by femga** [comment]
@Anterag1400 Updated music event list

**Comment by Anterag1400** [comment]
Thank you so much!

**Comment by Anterag1400** [comment]
Could I ask why some names were removed?

**Comment by Anterag1400** [comment]
Is there a way to find event names for RDR1 by any chance?

**Comment by femga** [comment]
@Anterag1400 I think so. Music natives exist in GTA5, most likely they exist in RDR1 as well. But I didn't buy RDR1.

**Comment by Anterag1400** [comment]
Someone is working on a tool to extract every music variations, and your findings are VERY helpful, so thank you very much. 

Though, some variations can't be extracted/autogenerated without reversing their names first. While  it's not a problem to have unknown names for vatiations, some others just can't be obtained. It can be done eventually manually, but it would still be useful to autogenerate everything.

To find more names, I usually do memory dumps like you probably did, but me and my friend who is working on this tool, have very old PC and can't get the game to run.

So, I'm asking if once again, not wanting to push you or be repetitive, could you could find more music event names please?
