### ISSUE TITLE
Download images not working

### ISSUE THREAD

**Issue by munafio** [femga/rdr3_discoveries#52]
Hi,
I have noticed that the option to download image with or without background from textures are not working, the domain or host is broken.

Examples:
https://github.com/femga/rdr3_discoveries/tree/master/useful_info_from_rpfs/textures/inventory_items
http://femga.com/images/samples/ui_textures_no_bg/inventory_items.zip
http://femga.com/images/samples/ui_textures_no_bg/inventory_items/_placeholder.png

**Comment by femga** [comment]
@munafio fixed
